//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace List_Drug
{
    using System;
    using System.Collections.Generic;
    
    public partial class Information_Drug
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Information_Drug()
        {
            this.Effect_Interactions = new HashSet<Effect_Interactions>();
            this.Interactions = new HashSet<Interactions>();
            this.Food_Interactions = new HashSet<Food_Interactions>();
        }
    
        public int Code_Drug { get; set; }
        public Nullable<int> Code_Group_Drug { get; set; }
        public string Name_En { get; set; }
        public string Name_Fa { get; set; }
        public string Pharmaceutical_Form { get; set; }
        public string Advices { get; set; }
    
        public virtual Group_Drug Group_Drug { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Effect_Interactions> Effect_Interactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Interactions> Interactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Food_Interactions> Food_Interactions { get; set; }
    }
}
