//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace List_Drug
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interactions
    {
        public int Code_Interactions { get; set; }
        public Nullable<int> Code_Drug { get; set; }
        public Nullable<int> Code_Durg_Interactions { get; set; }
        public string Name_Durg_Interactions { get; set; }
        public string Occurrence_Probability { get; set; }
        public string Sart_Time { get; set; }
        public string Complications { get; set; }
    
        public virtual Information_Drug Information_Drug { get; set; }
    }
}
