//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace List_Drug
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class List_DrugEntities : DbContext
    {
        public List_DrugEntities()
            : base("name=List_DrugEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Group_Drug> Group_Drug { get; set; }
        public virtual DbSet<Information_Drug> Information_Drug { get; set; }
        public virtual DbSet<Interactions> Interactions { get; set; }
        public virtual DbSet<Effect_Interactions> Effect_Interactions { get; set; }
        public virtual DbSet<Group_Food> Group_Food { get; set; }
        public virtual DbSet<Food_Interactions> Food_Interactions { get; set; }
    
        public virtual int Delete_Group_Drug(Nullable<int> code_Group_Drug)
        {
            var code_Group_DrugParameter = code_Group_Drug.HasValue ?
                new ObjectParameter("Code_Group_Drug", code_Group_Drug) :
                new ObjectParameter("Code_Group_Drug", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Group_Drug", code_Group_DrugParameter);
        }
    
        public virtual int Delete_Group_Food(Nullable<int> code_Group_Food)
        {
            var code_Group_FoodParameter = code_Group_Food.HasValue ?
                new ObjectParameter("Code_Group_Food", code_Group_Food) :
                new ObjectParameter("Code_Group_Food", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Group_Food", code_Group_FoodParameter);
        }
    
        public virtual int Insert_Effect_Interactions(Nullable<int> code_Drug, Nullable<int> code_Drug_Effect_Interactions, string name_Drug_Effect_Interactions, string probability_Occurrence)
        {
            var code_DrugParameter = code_Drug.HasValue ?
                new ObjectParameter("Code_Drug", code_Drug) :
                new ObjectParameter("Code_Drug", typeof(int));
    
            var code_Drug_Effect_InteractionsParameter = code_Drug_Effect_Interactions.HasValue ?
                new ObjectParameter("Code_Drug_Effect_Interactions", code_Drug_Effect_Interactions) :
                new ObjectParameter("Code_Drug_Effect_Interactions", typeof(int));
    
            var name_Drug_Effect_InteractionsParameter = name_Drug_Effect_Interactions != null ?
                new ObjectParameter("Name_Drug_Effect_Interactions", name_Drug_Effect_Interactions) :
                new ObjectParameter("Name_Drug_Effect_Interactions", typeof(string));
    
            var probability_OccurrenceParameter = probability_Occurrence != null ?
                new ObjectParameter("Probability_Occurrence", probability_Occurrence) :
                new ObjectParameter("Probability_Occurrence", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_Effect_Interactions", code_DrugParameter, code_Drug_Effect_InteractionsParameter, name_Drug_Effect_InteractionsParameter, probability_OccurrenceParameter);
        }
    
        public virtual int Insert_Food_Interactions(Nullable<int> code_Drug, Nullable<int> code_Group_Food, string complications, string descriptions, string name_Food_Interactions)
        {
            var code_DrugParameter = code_Drug.HasValue ?
                new ObjectParameter("Code_Drug", code_Drug) :
                new ObjectParameter("Code_Drug", typeof(int));
    
            var code_Group_FoodParameter = code_Group_Food.HasValue ?
                new ObjectParameter("Code_Group_Food", code_Group_Food) :
                new ObjectParameter("Code_Group_Food", typeof(int));
    
            var complicationsParameter = complications != null ?
                new ObjectParameter("Complications", complications) :
                new ObjectParameter("Complications", typeof(string));
    
            var descriptionsParameter = descriptions != null ?
                new ObjectParameter("Descriptions", descriptions) :
                new ObjectParameter("Descriptions", typeof(string));
    
            var name_Food_InteractionsParameter = name_Food_Interactions != null ?
                new ObjectParameter("Name_Food_Interactions", name_Food_Interactions) :
                new ObjectParameter("Name_Food_Interactions", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_Food_Interactions", code_DrugParameter, code_Group_FoodParameter, complicationsParameter, descriptionsParameter, name_Food_InteractionsParameter);
        }
    
        public virtual int Insert_Group_Drug(string name_Group_Drug)
        {
            var name_Group_DrugParameter = name_Group_Drug != null ?
                new ObjectParameter("Name_Group_Drug", name_Group_Drug) :
                new ObjectParameter("Name_Group_Drug", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_Group_Drug", name_Group_DrugParameter);
        }
    
        public virtual int Insert_Group_Food(string name_Group_Food)
        {
            var name_Group_FoodParameter = name_Group_Food != null ?
                new ObjectParameter("Name_Group_Food", name_Group_Food) :
                new ObjectParameter("Name_Group_Food", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_Group_Food", name_Group_FoodParameter);
        }
    
        public virtual int Insert_Information_Drug(Nullable<int> code_Drug, Nullable<int> code_Group_Drug, string name_En, string name_Fa, string pharmaceutical_Form, string advices)
        {
            var code_DrugParameter = code_Drug.HasValue ?
                new ObjectParameter("Code_Drug", code_Drug) :
                new ObjectParameter("Code_Drug", typeof(int));
    
            var code_Group_DrugParameter = code_Group_Drug.HasValue ?
                new ObjectParameter("Code_Group_Drug", code_Group_Drug) :
                new ObjectParameter("Code_Group_Drug", typeof(int));
    
            var name_EnParameter = name_En != null ?
                new ObjectParameter("Name_En", name_En) :
                new ObjectParameter("Name_En", typeof(string));
    
            var name_FaParameter = name_Fa != null ?
                new ObjectParameter("Name_Fa", name_Fa) :
                new ObjectParameter("Name_Fa", typeof(string));
    
            var pharmaceutical_FormParameter = pharmaceutical_Form != null ?
                new ObjectParameter("Pharmaceutical_Form", pharmaceutical_Form) :
                new ObjectParameter("Pharmaceutical_Form", typeof(string));
    
            var advicesParameter = advices != null ?
                new ObjectParameter("Advices", advices) :
                new ObjectParameter("Advices", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_Information_Drug", code_DrugParameter, code_Group_DrugParameter, name_EnParameter, name_FaParameter, pharmaceutical_FormParameter, advicesParameter);
        }
    
        public virtual int Insert_Interactions(Nullable<int> code_Drug, Nullable<int> code_Durg_Interactions, string name_Durg_Interactions, string occurrence_Probability, string sart_Time, string complications)
        {
            var code_DrugParameter = code_Drug.HasValue ?
                new ObjectParameter("Code_Drug", code_Drug) :
                new ObjectParameter("Code_Drug", typeof(int));
    
            var code_Durg_InteractionsParameter = code_Durg_Interactions.HasValue ?
                new ObjectParameter("Code_Durg_Interactions", code_Durg_Interactions) :
                new ObjectParameter("Code_Durg_Interactions", typeof(int));
    
            var name_Durg_InteractionsParameter = name_Durg_Interactions != null ?
                new ObjectParameter("Name_Durg_Interactions", name_Durg_Interactions) :
                new ObjectParameter("Name_Durg_Interactions", typeof(string));
    
            var occurrence_ProbabilityParameter = occurrence_Probability != null ?
                new ObjectParameter("Occurrence_Probability", occurrence_Probability) :
                new ObjectParameter("Occurrence_Probability", typeof(string));
    
            var sart_TimeParameter = sart_Time != null ?
                new ObjectParameter("Sart_Time", sart_Time) :
                new ObjectParameter("Sart_Time", typeof(string));
    
            var complicationsParameter = complications != null ?
                new ObjectParameter("Complications", complications) :
                new ObjectParameter("Complications", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_Interactions", code_DrugParameter, code_Durg_InteractionsParameter, name_Durg_InteractionsParameter, occurrence_ProbabilityParameter, sart_TimeParameter, complicationsParameter);
        }
    
        public virtual int Update_Effect_Interactions(Nullable<int> code_Effect_Interactions, Nullable<int> code_Drug, Nullable<int> code_Drug_Effect_Interactions, string name_Drug_Effect_Interactions, string probability_Occurrence)
        {
            var code_Effect_InteractionsParameter = code_Effect_Interactions.HasValue ?
                new ObjectParameter("Code_Effect_Interactions", code_Effect_Interactions) :
                new ObjectParameter("Code_Effect_Interactions", typeof(int));
    
            var code_DrugParameter = code_Drug.HasValue ?
                new ObjectParameter("Code_Drug", code_Drug) :
                new ObjectParameter("Code_Drug", typeof(int));
    
            var code_Drug_Effect_InteractionsParameter = code_Drug_Effect_Interactions.HasValue ?
                new ObjectParameter("Code_Drug_Effect_Interactions", code_Drug_Effect_Interactions) :
                new ObjectParameter("Code_Drug_Effect_Interactions", typeof(int));
    
            var name_Drug_Effect_InteractionsParameter = name_Drug_Effect_Interactions != null ?
                new ObjectParameter("Name_Drug_Effect_Interactions", name_Drug_Effect_Interactions) :
                new ObjectParameter("Name_Drug_Effect_Interactions", typeof(string));
    
            var probability_OccurrenceParameter = probability_Occurrence != null ?
                new ObjectParameter("Probability_Occurrence", probability_Occurrence) :
                new ObjectParameter("Probability_Occurrence", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_Effect_Interactions", code_Effect_InteractionsParameter, code_DrugParameter, code_Drug_Effect_InteractionsParameter, name_Drug_Effect_InteractionsParameter, probability_OccurrenceParameter);
        }
    
        public virtual int Update_Food_Interactions(Nullable<int> code_Food_Interactions, Nullable<int> code_Drug, Nullable<int> code_Group_Food, string complications, string descriptions, string name_Food_Interactions)
        {
            var code_Food_InteractionsParameter = code_Food_Interactions.HasValue ?
                new ObjectParameter("Code_Food_Interactions", code_Food_Interactions) :
                new ObjectParameter("Code_Food_Interactions", typeof(int));
    
            var code_DrugParameter = code_Drug.HasValue ?
                new ObjectParameter("Code_Drug", code_Drug) :
                new ObjectParameter("Code_Drug", typeof(int));
    
            var code_Group_FoodParameter = code_Group_Food.HasValue ?
                new ObjectParameter("Code_Group_Food", code_Group_Food) :
                new ObjectParameter("Code_Group_Food", typeof(int));
    
            var complicationsParameter = complications != null ?
                new ObjectParameter("Complications", complications) :
                new ObjectParameter("Complications", typeof(string));
    
            var descriptionsParameter = descriptions != null ?
                new ObjectParameter("Descriptions", descriptions) :
                new ObjectParameter("Descriptions", typeof(string));
    
            var name_Food_InteractionsParameter = name_Food_Interactions != null ?
                new ObjectParameter("Name_Food_Interactions", name_Food_Interactions) :
                new ObjectParameter("Name_Food_Interactions", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_Food_Interactions", code_Food_InteractionsParameter, code_DrugParameter, code_Group_FoodParameter, complicationsParameter, descriptionsParameter, name_Food_InteractionsParameter);
        }
    
        public virtual int Update_Group_Drug(Nullable<int> code_Group_Drug, string name_Group_Drug)
        {
            var code_Group_DrugParameter = code_Group_Drug.HasValue ?
                new ObjectParameter("Code_Group_Drug", code_Group_Drug) :
                new ObjectParameter("Code_Group_Drug", typeof(int));
    
            var name_Group_DrugParameter = name_Group_Drug != null ?
                new ObjectParameter("Name_Group_Drug", name_Group_Drug) :
                new ObjectParameter("Name_Group_Drug", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_Group_Drug", code_Group_DrugParameter, name_Group_DrugParameter);
        }
    
        public virtual int Update_Group_Food(Nullable<int> code_Group_Food, string name_Group_Food)
        {
            var code_Group_FoodParameter = code_Group_Food.HasValue ?
                new ObjectParameter("Code_Group_Food", code_Group_Food) :
                new ObjectParameter("Code_Group_Food", typeof(int));
    
            var name_Group_FoodParameter = name_Group_Food != null ?
                new ObjectParameter("Name_Group_Food", name_Group_Food) :
                new ObjectParameter("Name_Group_Food", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_Group_Food", code_Group_FoodParameter, name_Group_FoodParameter);
        }
    
        public virtual int Update_Information_Drug(Nullable<int> code_Drug, Nullable<int> code_Group_Drug, string name_En, string name_Fa, string pharmaceutical_Form, string advices)
        {
            var code_DrugParameter = code_Drug.HasValue ?
                new ObjectParameter("Code_Drug", code_Drug) :
                new ObjectParameter("Code_Drug", typeof(int));
    
            var code_Group_DrugParameter = code_Group_Drug.HasValue ?
                new ObjectParameter("Code_Group_Drug", code_Group_Drug) :
                new ObjectParameter("Code_Group_Drug", typeof(int));
    
            var name_EnParameter = name_En != null ?
                new ObjectParameter("Name_En", name_En) :
                new ObjectParameter("Name_En", typeof(string));
    
            var name_FaParameter = name_Fa != null ?
                new ObjectParameter("Name_Fa", name_Fa) :
                new ObjectParameter("Name_Fa", typeof(string));
    
            var pharmaceutical_FormParameter = pharmaceutical_Form != null ?
                new ObjectParameter("Pharmaceutical_Form", pharmaceutical_Form) :
                new ObjectParameter("Pharmaceutical_Form", typeof(string));
    
            var advicesParameter = advices != null ?
                new ObjectParameter("Advices", advices) :
                new ObjectParameter("Advices", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_Information_Drug", code_DrugParameter, code_Group_DrugParameter, name_EnParameter, name_FaParameter, pharmaceutical_FormParameter, advicesParameter);
        }
    
        public virtual int Update_Interactions(Nullable<int> code_Interactions, Nullable<int> code_Drug, Nullable<int> code_Durg_Interactions, string name_Durg_Interactions, string occurrence_Probability, string sart_Time, string complications)
        {
            var code_InteractionsParameter = code_Interactions.HasValue ?
                new ObjectParameter("Code_Interactions", code_Interactions) :
                new ObjectParameter("Code_Interactions", typeof(int));
    
            var code_DrugParameter = code_Drug.HasValue ?
                new ObjectParameter("Code_Drug", code_Drug) :
                new ObjectParameter("Code_Drug", typeof(int));
    
            var code_Durg_InteractionsParameter = code_Durg_Interactions.HasValue ?
                new ObjectParameter("Code_Durg_Interactions", code_Durg_Interactions) :
                new ObjectParameter("Code_Durg_Interactions", typeof(int));
    
            var name_Durg_InteractionsParameter = name_Durg_Interactions != null ?
                new ObjectParameter("Name_Durg_Interactions", name_Durg_Interactions) :
                new ObjectParameter("Name_Durg_Interactions", typeof(string));
    
            var occurrence_ProbabilityParameter = occurrence_Probability != null ?
                new ObjectParameter("Occurrence_Probability", occurrence_Probability) :
                new ObjectParameter("Occurrence_Probability", typeof(string));
    
            var sart_TimeParameter = sart_Time != null ?
                new ObjectParameter("Sart_Time", sart_Time) :
                new ObjectParameter("Sart_Time", typeof(string));
    
            var complicationsParameter = complications != null ?
                new ObjectParameter("Complications", complications) :
                new ObjectParameter("Complications", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_Interactions", code_InteractionsParameter, code_DrugParameter, code_Durg_InteractionsParameter, name_Durg_InteractionsParameter, occurrence_ProbabilityParameter, sart_TimeParameter, complicationsParameter);
        }
    
        public virtual int Delete_Information_Drug(Nullable<int> code_Drug)
        {
            var code_DrugParameter = code_Drug.HasValue ?
                new ObjectParameter("Code_Drug", code_Drug) :
                new ObjectParameter("Code_Drug", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Information_Drug", code_DrugParameter);
        }
    
        public virtual int Delete_Effect_Interactions(Nullable<int> code_Drug)
        {
            var code_DrugParameter = code_Drug.HasValue ?
                new ObjectParameter("Code_Drug", code_Drug) :
                new ObjectParameter("Code_Drug", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Effect_Interactions", code_DrugParameter);
        }
    
        public virtual int Delete_Food_Interactions(Nullable<int> code_Drug)
        {
            var code_DrugParameter = code_Drug.HasValue ?
                new ObjectParameter("Code_Drug", code_Drug) :
                new ObjectParameter("Code_Drug", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Food_Interactions", code_DrugParameter);
        }
    
        public virtual int Delete_Interactions(Nullable<int> code_Drug)
        {
            var code_DrugParameter = code_Drug.HasValue ?
                new ObjectParameter("Code_Drug", code_Drug) :
                new ObjectParameter("Code_Drug", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Interactions", code_DrugParameter);
        }
    }
}
